controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
# app_commant:
#     path: /Games/commant
#     controller: App\Controller\GameController::commant
#     methods: [GET, POST]